### ISSUE TITLE
[Feature Request] GitHub action for cross-platform compiling 

### ISSUE THREAD

**Issue by elpekenin** [qmk/qmk_xap#7]
### Description

Tauri doesnt support cross-compiling (yet) Thus, they provide GitHub actions to get the compilations done, [info on their docs](https://tauri.app/v1/guides/building/cross-platform/), im not making a PR for two reasons:
- I have no idea how Actions work/are setup
- I've manually compiled on Windows and while i could install the output file, the `.exe` didn't even open afterwards. So we really should get things configured/tested before getting auto-compilations going into non-working code.

**Comment by KarlK90** [comment]
Hi, @elpekenin we now have automated cross compiling builds using tauris recommended github actions. The file is in the under `.github/workflows/tauri-release.yml`. Closing this now :slightly_smiling_face:
